<a id=top-page></a>
# `pykitPIV` demo: Computing sensory cues and rewards

In this Jupyter notebook, we showcase the possible sensory cues and rewards available in the machine learning module (`pykitPIV.ml`).

The user can use the `Cues` class and the `Rewards` class.

<div class="alert alert-block alert-info" style="margin-top: 20px">
<font size="3"><strong>Table of contents:</strong></font>
<br>
<ol>
    <li><a href="#cues">Sensory cues</a></li>
        <ul>
        <li><a href="#cues-ds">Create a custom displacement field to test all sensory cues computation</a></li>
        <li><a href="#cues-sampled-vectors">Sampled vectors</a></li>
        <li><a href="#cues-sampled-magnitude">Sampled magnitude</a></li>
        <li><a href="#cues-sampled-divergence">Sampled divergence</a></li>
        <li><a href="#cues-sampled-vorticity">Sampled vorticity</a></li>
        <li><a href="#cues-sampled-q-criterion">Sampled Q-criterion</a></li>
        </ul>
    <li><a href="#rewards">Rewards</a></li>
        <ul>
        <li><a href="#rewards-ds">Create a custom displacement field to test rewards computation</a></li>
        <li><a href="#rewards-divergence">Divergence</a></li>
        <li><a href="#rewards-vorticity">Vorticity</a></li>
        <li><a href="#rewards-q-criterion">Q-criterion</a></li>
        </ul>
</ol>
<p></p>
</div>
<br>

***

In [1]:
from pykitPIV import FlowField
from pykitPIV.ml import Cues, Rewards
import matplotlib.pyplot as plt
import cmcrameri.cm as cmc
import numpy as np

2025-05-27 15:11:38.945158: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
save_images = False
filename = None

<a id=cues></a>
***

## Sensory cues

[Go to the top](#top-page)

All sensory cues are vectors, $\mathbf{c}$, have shape $(1, N)$, which is the applicable shape to pass as an input to a classic neural network.

<a id=cues-ds></a>

### Create a custom displacement field to test all sensory cues computation

[Go to the top](#top-page)

In [3]:
flowfield = FlowField(n_images=1,
                      size=(128,128),
                      size_buffer=0,
                      random_seed=100)

flowfield.generate_random_velocity_field(displacement=(0, 10),
                                         gaussian_filters=(10, 30),
                                         n_gaussian_filter_iter=6)

displacement_field = flowfield.velocity_field

Instantiate an object of the `Cues` class:

In [4]:
cues_obj = Cues(verbose=False,
                random_seed=None,
                sample_every_n=30,
                normalize_displacement_vectors=False)

<a id=cues-sampled-vectors></a>

### Sampled vectors

[Go to the top](#top-page)

In [5]:
cues = cues_obj.sampled_vectors(displacement_field=displacement_field)

In [6]:
cues.shape

(1, 50)

<a id=cues-sampled-vectors></a>

### Sampled magnitude

[Go to the top](#top-page)

In [7]:
cues = cues_obj.sampled_magnitude(displacement_field=displacement_field)

In [8]:
cues.shape

(1, 25)

<a id=cues-sampled-divergence></a>

### Sampled divergence

[Go to the top](#top-page)

In [9]:
cues = cues_obj.sampled_divergence(displacement_field=displacement_field)

In [10]:
cues.shape

(1, 25)

In [11]:
cues

array([[ 0.0004795 ,  0.05030768, -0.03374612, -0.11076905, -0.03780083,
        -0.0597983 , -0.00467119, -0.0518349 , -0.12713167, -0.09793702,
        -0.03530432, -0.00375742, -0.02145311, -0.06544079, -0.06996054,
         0.03392005,  0.02124997,  0.00556867, -0.00946141, -0.03535474,
         0.0155924 , -0.01278111,  0.00077238,  0.02714297,  0.00087355]])

<a id=cues-sampled-vorticity></a>

### Sampled vorticity

[Go to the top](#top-page)

In [12]:
cues = cues_obj.sampled_vorticity(displacement_field=displacement_field)

In [13]:
cues.shape

(1, 25)

In [14]:
cues

array([[ 0.00020826,  0.02603601, -0.01189934, -0.03582323, -0.01323051,
        -0.02760983,  0.0208438 , -0.02776932, -0.10799973, -0.10915376,
        -0.0327724 ,  0.0411175 , -0.01373248, -0.12167284, -0.10608897,
        -0.04476739,  0.02841456, -0.02675593, -0.1325723 , -0.08980546,
        -0.01258821,  0.03186233, -0.04162488, -0.13281771, -0.05743644]])

<a id=cues-sampled-q-criterion></a>

### Sampled Q-criterion

[Go to the top](#top-page)

In [15]:
cues = cues_obj.sampled_q_criterion(displacement_field=displacement_field)

In [16]:
cues.shape

(1, 25)

In [17]:
cues

array([[-1.05727409e-05, -1.23176324e-03, -4.75499677e-04,
        -5.48665475e-03, -5.17829279e-04, -1.82112160e-03,
        -2.80656231e-03, -3.49104641e-04,  1.49044022e-03,
         1.53015919e-03, -5.17751950e-04, -1.45960038e-03,
        -1.06945900e-04,  5.95194539e-03,  3.14332026e-03,
        -2.27747267e-04, -1.81875713e-03,  3.22857990e-04,
         6.92714514e-03,  3.21447082e-03, -1.38320166e-04,
        -5.42372180e-04,  5.58470205e-04,  4.86171254e-03,
         1.34096907e-03]])

<a id=rewards></a>

***

## Rewards

[Go to the top](#top-page)

All rewards are single numbers (integers or floats).

<a id=rewards-ds></a>

### Create a custom displacement field to test all rewards computation

[Go to the top](#top-page)

In [18]:
flowfield = FlowField(n_images=1,
                      size=(128,128),
                      size_buffer=0,
                      random_seed=100)

flowfield.generate_random_velocity_field(displacement=(0, 10),
                                         gaussian_filters=(10, 30),
                                         n_gaussian_filter_iter=6)

displacement_field = flowfield.velocity_field

Instantiate an object of the `Rewards` class:

In [19]:
rewards = Rewards(verbose=True,
                  random_seed=None)

<a id=rewards-divergence></a>

### Divergence

[Go to the top](#top-page)

We design a custom transformation that looks for regions of high divergence (either positive or negative) and computes the maximum absolute value of divergence in that region:

In [20]:
def transformation(div):
    return np.max(np.abs(div))

In [21]:
reward = rewards.divergence(vector_field=displacement_field,
                            transformation=transformation)

0.13611737879932362


<a id=rewards-vorticity></a>

### Vorticity

[Go to the top](#top-page)

We design a custom transformation that looks for regions of high vorticity (either positive or negative) and computes the mean absolute value of vorticity in that region:

In [22]:
def transformation(vort):
    return np.mean(np.abs(vort))

In [23]:
reward = rewards.vorticity(vector_field=displacement_field,
                           transformation=transformation)

0.056873321781106975


<a id=rewards-q-criterion></a>

### Q-criterion

[Go to the top](#top-page)

We design a custom transformation that looks for vorticity-dominated regions (as opposed to shear-dominated regions) and computes the maximum value of the Q-criterion in that region:

In [24]:
def transformation(Q):
    Q = np.max(Q.clip(min=0))
    return Q

In [25]:
reward = rewards.q_criterion(vector_field=displacement_field,
                             transformation=transformation)

0.00829011539041633


***

© K. Zdybał, C. Mucignat, S. Kunz, I. Lunati (2025)