<a id=top-page></a>
# `pykitPIV` demo: Test computing sensory cues and rewards

In this Jupyter notebook, we showcase the possible sensory cues and rewards available in the machine learning module (`pykitPIV.ml`).

The user can use the `Cues` class and the `Rewards` class.

<div class="alert alert-block alert-info" style="margin-top: 20px">
<font size="3"><strong>Table of contents:</strong></font>
<br>
<ol>

</ol>
<p></p>
</div>
<br>

***

In [1]:
from pykitPIV import FlowField
from pykitPIV.ml import Cues, Rewards
import matplotlib.pyplot as plt
import cmcrameri.cm as cmc
import numpy as np

2025-05-07 15:43:54.308647: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [ ]:
save_images = False
filename = None

***

## Sensory cues

All sensory cues are vectors, $\mathbf{c}$, have shape $(1, N)$, which is the applicable shape to pass as an input to a classic neural network.

### Create a custom displacement field to test all sensory cues computation

In [2]:
flowfield = FlowField(n_images=1,
                      size=(128,128),
                      size_buffer=0,
                      random_seed=100)

flowfield.generate_random_velocity_field(displacement=(0, 10),
                                         gaussian_filters=(10, 30),
                                         n_gaussian_filter_iter=6)

displacement_field = flowfield.velocity_field

Instantiate an object of the Cues class:

In [3]:
cues_obj = Cues(verbose=False,
                random_seed=None,
                sample_every_n=30,
                normalize_displacement_vectors=False)

### Sampled vectors

In [4]:
cues = cues_obj.sampled_vectors(displacement_field=displacement_field)

In [5]:
cues.shape

(1, 50)

### Sampled magnitude

In [6]:
cues = cues_obj.sampled_magnitude(displacement_field=displacement_field)

In [7]:
cues.shape

(1, 25)

### Sampled divergence

In [8]:
cues = cues_obj.sampled_divergence(displacement_field=displacement_field)

In [9]:
cues.shape

(1, 25)

In [10]:
cues

array([[ 0.0004795 ,  0.05030768, -0.03374612, -0.11076905, -0.03780083,
        -0.0597983 , -0.00467119, -0.0518349 , -0.12713167, -0.09793702,
        -0.03530432, -0.00375742, -0.02145311, -0.06544079, -0.06996054,
         0.03392005,  0.02124997,  0.00556867, -0.00946141, -0.03535474,
         0.0155924 , -0.01278111,  0.00077238,  0.02714297,  0.00087355]])

### Sampled vorticity

In [11]:
cues = cues_obj.sampled_vorticity(displacement_field=displacement_field)

In [12]:
cues.shape

(1, 25)

In [13]:
cues

array([[ 0.00020826,  0.02603601, -0.01189934, -0.03582323, -0.01323051,
        -0.02760983,  0.0208438 , -0.02776932, -0.10799973, -0.10915376,
        -0.0327724 ,  0.0411175 , -0.01373248, -0.12167284, -0.10608897,
        -0.04476739,  0.02841456, -0.02675593, -0.1325723 , -0.08980546,
        -0.01258821,  0.03186233, -0.04162488, -0.13281771, -0.05743644]])

### Sampled Q-criterion

In [14]:
cues = cues_obj.sampled_q_criterion(displacement_field=displacement_field)

In [15]:
cues.shape

(1, 25)

In [16]:
cues

array([[-1.05727409e-05, -1.23176324e-03, -4.75499677e-04,
        -5.48665475e-03, -5.17829279e-04, -1.82112160e-03,
        -2.80656231e-03, -3.49104641e-04,  1.49044022e-03,
         1.53015919e-03, -5.17751950e-04, -1.45960038e-03,
        -1.06945900e-04,  5.95194539e-03,  3.14332026e-03,
        -2.27747267e-04, -1.81875713e-03,  3.22857990e-04,
         6.92714514e-03,  3.21447082e-03, -1.38320166e-04,
        -5.42372180e-04,  5.58470205e-04,  4.86171254e-03,
         1.34096907e-03]])

***

© K. Zdybał, C. Mucignat, S. Kunz, I. Lunati (2025)